config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  get "/updates", to: "pages#updates"

  get "suggested_friends", to: "pages#suggested_friends"

  resources :saved_routes, except: [:update, :edit, :new, :create]
  resources :friendships, only: [:new, :create, :index] do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :coaches do
    member do
      post 'save_program'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :routes, only: [:index, :show] do
    member do
    get 'share', to: 'share_routes#share'
    post 'share_send', to: 'share_routes#share_send'
    end
    resources :saved_routes, only: [:create]
  end

  resources :users, only: [:show] do
    member do
      patch :update_biography, to: "users#update_biography", as: :update_biography
    end
    resources :chatrooms, only: [:create]
  end

  resources :chatrooms, except: [:edit, :update, :new, :create] do
    resources :messages, only: :create
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #validates :category, inclusion: { in: ["Beginner", "Intermediate", "Novice", "Marathon", "Athlete"] }
  has_many :chatrooms
  has_many :coaches
  has_many :messages

  has_many :session_participants
  has_many :saved_routes
  has_many :routes, through: :saved_routes
  has_one_attached :photo

  def friendships
    Friendship.where(user_one: self) + Friendship.where(user_two: self)
  end

  def friends
    friendships.map do |friendship|
      if friendship.user_one == self
        friendship.user_two
      else
        friendship.user_one
      end
    end
  end

  def friendship_with(user)
    friendships.find do |friendship|
      friendship.users.sort == [self, user].sort
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    if params[:user][:photo].present?
      result = Cloudinary::Uploader.upload(params[:user][:photo].path)
      resource.photo.key = result['public_id']
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update_biography]

  def show
    @suggested_friends = User.where.not(id: current_user.id)
    @new_friendship = Friendship.new
    @coaches = current_user.coaches.where.not(program_content: [nil, ''])
  end

  def update_biography
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:id, :photo, :biography)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/show.html.erb
<div class="users-header">
  <% if current_user.id == @user.id %>
  <div class="logout">
    <%= link_to("Logout", destroy_user_session_path, class: 'btn btn-success', data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }) %>
  </div>
  <% end %>
  <% if @user.photo.key %>
    <%= cl_image_tag(@user.photo.key, class: "avatar-large", width: 56, height: 56) %>
  <% else %>
    <i class="fa-solid fa-user"></i>
  <% end %>
  <h2><%= @user.first_name %> <%= @user.last_name %></h2>
  <h4><%= Time.now.year - @user.date_of_birth.year %> years old</h4>
  <h4><%= @user.running_level %> Runner</h4>
  <h4><%= @user.state %></h4>
  <% if current_user.id != @user.id %>
    <div class="actions">
      <%= link_to("", user_chatrooms_path(@user), data: { turbo_method: :post }, class: "fa-solid fa-message") %>

      <%= simple_form_for @new_friendship do |form| %>
        <%= form.input :user_one_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= form.input :user_two_id, as: :hidden, input_html: { value: @user.id } %>
        <%= button_tag(type: 'submit', style: 'border-style: none') do %>
        <i class="fa-solid fa-user-plus"></i>
        <% link_to  %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <% if current_user.id == @user.id %>
    <%= link_to("", friendships_path, data: { turbo_method: :get }, class: "fa-solid fa-user-group", style:"color: #0bad7c; font-size: 2em;") %>
    <div class="biography" id=<%= @user.id %> data-controller="biography">
      <div class="action">
        <i class="fa-solid fa-pencil"></i>
      </div>
      <div class="text" data-action="click->biography#modifyBiography" data-biography-target="text">
        <%= @user.biography %>
      </div>
      <div class="form d-none" data-biography-target="form">
        <%= simple_form_for @user, url: update_biography_user_path(@user), action: "submit->insert-in-list#saveText" do |f| %>
          <%= f.input :biography, as: :text %>
          <%= f.button :submit, "Save" %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="biography">
      <div class="text">
        <%= @user.biography %>
      </div>
    </div>
  <% end %>
</div>

<h2 style="text-align: center;"><strong>Your Training Programs:</strong></h2>

<div class="row">
  <% if @coaches.any? %>
  <% @coaches.each do |coach| %>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-title"><%= coach.name %></h5>
          <p class="card-text">Duration/Date: <%= coach.duration %></p>
          <p class="card-text">Race/Goal Distance: <%= coach.distance %></p>
          <%= link_to 'View Program', coach_path(coach), class: 'btn btn-success' %>
          <%= link_to 'Delete Program', coach_path(coach),class: 'btn btn-success', data: { turbo_method: :delete, turbo_confirm: "Are you sure to delete your route?"} %>
        </div>
      </div>
    </div>
  <% end %>
  <% else %>
    <p>No training programs available at the moment. Please try again later.</p>
<%end%>
</div>