config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  get "/updates", to: "pages#updates"

  get "suggested_friends", to: "pages#suggested_friends"

  resources :saved_routes, except: [:update, :edit, :new, :create]
  resources :friendships, only: [:new, :create, :index] do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :coaches do
    member do
      post 'save_program'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :routes, only: [:index, :show] do
    member do
    get 'share', to: 'share_routes#share'
    post 'share_send', to: 'share_routes#share_send'
    end
    resources :saved_routes, only: [:create]
  end

  resources :users, only: [:show] do
    member do
      patch :update_biography, to: "users#update_biography", as: :update_biography
    end
    resources :chatrooms, only: [:create]
  end

  resources :chatrooms, except: [:edit, :update, :new, :create] do
    resources :messages, only: :create
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">

    <%= link_to(root_path) do |route| %>
      Home <i class="fa-solid fa-location-dot"></i>
    <% end %>

     <%= link_to(saved_routes_path) do |route| %>
       Routes <i class="fa-regular fa-bookmark"></i>
    <% end %>

    <%= link_to(updates_path) do |route| %>
      Updates <i class="fa-regular fa-bell"></i></a>
    <% end %>

    <%= link_to(new_coach_path) do |route| %>
      Coach <i class="fa-solid fa-person-running"></i></a>
    <% end %>

  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar px-3">
    <div class="logo-title">
      <%= link_to image_tag("navbar_logo.png", alt: "navbar-logo"), root_path %>
      <h4>DefendHer RUN</h4>
    </div>
    <div class="actions">
      <%= link_to("", chatrooms_path, class:"fa-solid fa-message") %>
      <%= link_to("", user_path(current_user), class: "fa-solid fa-user fa-lg") %>
    </div>
  </div>
<% else %>
  <div class="navbar px-3">
    <div class="logo-title">
      <%= link_to image_tag("navbar_logo.png", alt: "navbar-logo", size: "70x70"), root_path %>
      <h4>DefendHer RUN</h4>
    </div>
    <div class="actions">
      <%= link_to("Sign Up", new_user_registration_path, id: "action") %>
      <%= link_to("Log In", new_user_session_path, id: "action") %>
    </div>
  </div>
<% end %>