config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  get "/updates", to: "pages#updates"

  get "suggested_friends", to: "pages#suggested_friends"

  resources :saved_routes, except: [:update, :edit, :new, :create]
  resources :friendships, only: [:new, :create, :index] do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :coaches do
    member do
      post 'save_program'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :routes, only: [:index, :show] do
    member do
    get 'share', to: 'share_routes#share'
    post 'share_send', to: 'share_routes#share_send'
    end
    resources :saved_routes, only: [:create]
  end

  resources :users, only: [:show] do
    member do
      patch :update_biography, to: "users#update_biography", as: :update_biography
    end
    resources :chatrooms, only: [:create]
  end

  resources :chatrooms, except: [:edit, :update, :new, :create] do
    resources :messages, only: :create
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/pages/_info_window.html.erb
<h2><%= route.address %></h2>
<p><%= route.distance %></p>

app/views/pages/_marker.html.erb
<%= image_tag "logo.jpg", height: 30, width: 30, alt: "Logo" %>

app/views/pages/home.html.erb
<div class="container">
  <% if user_signed_in? %>
    <div class="row justify-content-center">
      <div class="col-sm-8 my-3">
        <%= form_with url: root_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for a running route"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="title">
    <h1>Run Safer, Together</h1>
  </div>
  <div class="subtitle my-3">
    <h4>Find a friend to run with or find a safe running route!</h4>
  </div>
  <div class="d-flex flex-column justify-content-center">
  </div>

  <div class="d-flex justify-content-center my-4">
    <%= link_to "Find a Running Buddy", suggested_friends_path, class: "btn btn-success" %>
  </div>
  <% if !@searched_routes %>
    <h3 class="my-2">Explore Running Routes:</h3>
  <% else %>
    <% if @searched_routes.length > 0 %>
      <h3>Explore <%= params["query"].capitalize! %> routes</h3>
    <% else %>
      <h3>No routes found for <%= params["query"]%></h3>
    <% end %>
  <% end %>
  <div class="container">
    <% if !@searched_routes %>
      <% @routes.take(3).each do |route| %>
        <%= link_to(route_path(route)) do %>
          <div class="card-trip">
            <% if route.image.present? %>
              <%= image_tag route.image, alt: "Trip Image" %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" alt="Trip Image"/>
            <% end %>
            <div class="card-trip-infos">
              <div class="route-details">
                <h2><%= route.name %></h2>
                <p>Address: <%= route.address %></p>
                <p>Distance: <%= route.distance %> km</p>
                <p>Description: <%= route.description %></p>
              </div>
              <h2 class="card-trip-pricing"><%= route.distance %> km</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <% @searched_routes.each do |route| %>
        <div class="card-trip">
          <% if route.image.present? %>
            <%= image_tag route.image, alt: "Trip Image" %>
          <% else %>
            <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" alt="Trip Image"/>
          <% end %>
          <div class="card-trip-infos">
            <div class="route-details">
              <h2><%= link_to route.name, route_path(route) %></h2>
              <p>Address: <%= route.address %></p>
              <p>Distance: <%= route.distance %> km</p>
              <p>Description: <%= route.description %></p>
            </div>
            <h2 class="card-trip-pricing"><%= route.distance %> km</h2>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<div class="d-flex my-4 justify-content-center">
  <%= link_to "View All Routes", routes_path, class: "btn btn-success" %>
</div>

  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/pages/saved_routes.html.erb
<h1>Saved routes index page</h1>

<ul>
  <% @routes.each do |route| %>
    <h3><% route.address %></h3>
    <li>
      <%= link_to route.address, route_path(route) %>
    </li>
  <% end %>
</ul>

app/views/pages/suggested_friends.html.erb
<h1>Run Safer, Together</h1>
  <h4>Find a friend to run with!</h4>
  <div class="container">
    <% @users.each do |user| %>
      <% if user!= current_user %>
        <%= link_to user_path(user) do %>
          <div class="card-product">
            <% if user.photo.key %>
              <%= cl_image_tag(user.photo.key, class: "avatar-large", width: 56, height: 56) %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" alt="Default Profile Picture"/>
            <% end %>

            <div class="card-product-infos">
              <h2><%= user.first_name %> <%= user.last_name %></h2>
              <p><%= user.running_level %> Runner</p>
              <p><%= user.state %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

app/views/pages/updates.html.erb
<div class="container">
  <h1>Notifications</h1>
</div>

<% if @updates.any? %>
  <div class="cards">
    <% @updates.each do |update| %>
      <% if update.is_a?(Message) %>
        <%= link_to chatroom_path(update.chatroom) do %>
          <div class="card-product">
            <% if update.user.photo.present? %>
              <%= cl_image_tag(update.user.photo.key, id: "profile", class: "avatar-bordered" ) %>
            <% else %>
              <img src="https://kitt.lewagon.com/placeholder/users/cveneziani" class="avatar-bordered" />
            <% end %>
            <div class="card-product-infos">
              <h2 class="message-updates">New message from <%= update.user.first_name %></h2>
              <p><%= update.content %></p>
            </div>
          </div>
        <% end %>

      <% elsif update.is_a?(Friendship) %>
        <div class="card-product">
          <% if update.user_one.photo.present? %>
            <%= cl_image_tag(update.user_one.photo.key, id: "profile", class: "avatar-bordered") %>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/cveneziani" class="avatar-bordered" />
          <% end %>
          <div class="card-product-infos">
            <h2>Pending Friend Request</h2>
            <p><%= update.user_one.first_name %> <%= update.user_one.last_name %></p>
            <div class="friendship-actions mt-2">
              <%= link_to "Accept", accept_friendship_path(update), data: { turbo_method: :patch }, class: "btn btn-success btn-sm me-2" %>
              <%= link_to "Reject", reject_friendship_path(update), data: { turbo_method: :patch }, class: "btn btn-danger btn-sm" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <p>No notifications available.</p>
<% end %>