config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  get "/updates", to: "pages#updates"

  get "suggested_friends", to: "pages#suggested_friends"

  resources :saved_routes, except: [:update, :edit, :new, :create]
  resources :friendships, only: [:new, :create, :index] do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :coaches do
    member do
      post 'save_program'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :routes, only: [:index, :show] do
    member do
    get 'share', to: 'share_routes#share'
    post 'share_send', to: 'share_routes#share_send'
    end
    resources :saved_routes, only: [:create]
  end

  resources :users, only: [:show] do
    member do
      patch :update_biography, to: "users#update_biography", as: :update_biography
    end
    resources :chatrooms, only: [:create]
  end

  resources :chatrooms, except: [:edit, :update, :new, :create] do
    resources :messages, only: :create
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/route.rb
class Route < ApplicationRecord
  validates :address, presence: true
  validates :distance, presence: true
  has_many :saved_routes
  scope :running_sessions, -> { where(active: true) }
  geocoded_by :address
  #has_one_attached :image
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
before_action :set_route, only: [:show]

  def index
    @routes = Route.all
    @markers = @routes.geocoded.map do |route|
      {
        lat: route.latitude,
        lng: route.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {route: route}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    @marker = [
      {
        lat: @route.latitude,
        lng: @route.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { route: @route }),
        marker_html: render_to_string(partial: "marker")
      }
    ]
  end

  def saved_routes
    @routes = current_user.routes
  end

  private

  def route_params
    params.require(:route).permit(:address, :distance, :image)
  end

  def set_route
    @route = Route.find(params[:id])
  end
end

app/views/routes/index.html.erb
<!-- Top Section: List of Running Routes -->
<h1>Running Routes</h1>
<div class="container">
  <% @routes.each do |route| %>
    <div class="card-trip">
      <!-- Placeholder image for the route or a dynamic image if available -->
      <% if route.image.present? %>
            <%= image_tag route.image, alt: "Trip Image" %>
        <%else%>
       <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" alt= "Trip Image"/>
      <% end %>

      <div class="card-trip-infos">
        <div class="route-details">
          <!-- Route title linked to its detailed page -->
          <h2><%= link_to route.name, route_path(route) %></h2>

          <!-- Distance and description of the route -->
          <p>Address: <%= route.address %></p>
          <p>Distance: <%= route.distance %> km</p>
          <p>Description: <%= route.description %></p>


        </div>

        <!-- Optional pricing and user info -->
        <h2 class="card-trip-pricing"><%= route.distance %> km </h2>
      </div>
    </div>
  <% end %>
</div>

<!-- Bottom Section: Additional Content or Placeholder -->
<div class="bottom-section">
  <!-- You can place additional content or another section here -->
  <h2>Explore More Routes</h2>
  <p>Discover more exciting routes and adventures tailored to your preferences!</p>
  <!-- Optionally, include more links or content -->
</div>


  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/routes/show.html.erb
<h1><%= @route.name %></h1>


<div class="text-center">
  <%= image_tag @route.image, alt: "#{@route.name} image", class: "img-fluid" %>
</div>

<div class="text-left">
  <p>Address: <%= @route.address %></p>
  <p>Distance: <%= @route.distance %> km</p>
  <p>Description: <%= @route.description %></p>
</div>

<div class="text-center", style="padding:20px;">
  <%= link_to 'All Routes', routes_path, class: 'btn btn-success' %>
  <%= link_to 'Save Route', route_saved_routes_path(@route), data: { turbo_method: :post },class: 'btn btn-success' %>
  <%= link_to 'Share', share_route_path(@route) , class: 'btn btn-success' %>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>